name: Bug Report
description: File a bug report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        We appreciate it if you can fill in each section completely.
  - type: input
    id: search_terms
    attributes:
      label: Search Terms
      description: Which terms did you use when trying to find an existing bug report?
      placeholder: e.g. "function option return", "inline style attribute", "mutually exclusive"
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which library components are related to the problem?
      multiple: true
      options:
        - Options
        - Parser
        - Formatter
        - Validator
        - Styles
  - type: input
    id: playground
    attributes:
      label: Playground Link
      description: A link to a tsargp playground which shows this behavior (click "Share URL").
      placeholder: https://trulysimple.dev/tsargp/play#E4UwLgrsB2AEDeBfA3EA...
  - type: textarea
    id: code
    attributes:
      label: Sample code
      description: If you have sample code instead of a playground link, please paste it here.
      placeholder: This will be automatically formatted into code, so no need for backticks.
      value: // Your code here
      render: ts
  - type: textarea
    id: what_happened
    attributes:
      label: Bug description
      description: Tell us, what happened and what is the expected behavior?
      placeholder: You can place code samples here as well (if not already provided).
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: If you got an unexpected error, please paste the relevant log output here.
      placeholder: This will be automatically formatted into code, so no need for backticks.
      render: shell
